//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class travelEntities : DbContext
    {
        public travelEntities()
            : base("name=travelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<contact> contacts { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Hotel_images> Hotel_images { get; set; }
        public virtual DbSet<Resort> Resorts { get; set; }
        public virtual DbSet<Resort_images> Resort_images { get; set; }
        public virtual DbSet<Resturant> Resturants { get; set; }
        public virtual DbSet<Resturant_images> Resturant_images { get; set; }
        public virtual DbSet<tbl_travel> tbl_travel { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
        public virtual DbSet<tou_images> tou_images { get; set; }
        public virtual DbSet<touristSpot> touristSpots { get; set; }
    }
}
