//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resturant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resturant()
        {
            this.Resturant_images = new HashSet<Resturant_images>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public string contact { get; set; }
        public string Website { get; set; }
        public string Facilities { get; set; }
        public string Table_available { get; set; }
        public Nullable<int> c_id { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resturant_images> Resturant_images { get; set; }
    }
}
