//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_travel
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> seat_available { get; set; }
        public string @class { get; set; }
        public string from_route { get; set; }
        public string to_route { get; set; }
        public string pic { get; set; }
    
        public virtual city city { get; set; }
    }
}
