//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class touristSpot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public touristSpot()
        {
            this.tou_images = new HashSet<tou_images>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> c_id { get; set; }
        public string Address { get; set; }
        public string postalcode { get; set; }
        public string detail { get; set; }
    
        public virtual city city { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tou_images> tou_images { get; set; }
    }
}
